# Generated by Django 5.2.8 on 2025-12-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='hours_rendered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hours for the day', max_digits=5, null=True),
        ),
    ]
