# Generated by Django 5.2.8 on 2025-12-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailylog_is_verified_alter_dailylog_hours_rendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='report_type',
            field=models.CharField(choices=[('weekly_report', 'Weekly Report'), ('narrative', 'Narrative Report'), ('resume', 'Resume/CV'), ('moa', 'Memorandum of Agreement'), ('reflection', 'Reflection Paper'), ('other', 'Other')], max_length=50),
        ),
    ]
