# Generated by Django 5.2.8 on 2026-01-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(default='Cavite State University - Bacoor Campus', max_length=100),
        ),
    ]
