# Generated by Django 5.2.8 on 2026-01-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studentprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='school',
            field=models.CharField(default='Cavite State University - Bacoor Campus', max_length=100),
        ),
    ]
